site_name: Marvin Documentation
site_description: Intelligent PRD to AI-Coding-Task Converter
site_author: Marvin Team
site_url: https://moinsen-dev.github.io/marvin/
repo_url: https://github.com/moinsen-dev/marvin
repo_name: marvin
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Marvin Team

# Theme configuration
theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  # logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Use Cases:
    - Overview: use-cases/index.md
    - Startup MVP: use-cases/startup-mvp.md
    - API Development: use-cases/api-development.md
    - Enterprise Features: use-cases/enterprise-features.md
    - Frontend Apps: use-cases/frontend-apps.md
    - Microservices: use-cases/microservices.md
    - Database Design: use-cases/database-design.md
    - Testing Strategy: use-cases/testing-strategy.md
    - DevOps & CI/CD: use-cases/devops-cicd.md
  - Guides:
    - AI Coding Improvements: guides/ai-coding-improvements.md
    - Writing Effective PRDs: guides/writing-effective-prds.md
    - Best Practices: guides/best-practices.md
    - Team Workflows: guides/team-workflows.md
    - AI Tool Integration: guides/ai-integration.md
  - Case Studies:
    - Before & After: case-studies/before-after-comparison.md
    - Success Stories: case-studies/success-stories.md
  - User Guide:
    - Processing PRDs: user-guide/processing-prds.md
    - Understanding Templates: user-guide/templates.md
    - CLI Usage: user-guide/cli-usage.md
  - Architecture:
    - Overview: architecture/overview.md
    - Domain Models: architecture/domain-models.md
    - Agents: architecture/agents.md
    - Adapters: architecture/adapters.md
  - API Reference:
    - REST API: api/rest-api.md
    - Python SDK: api/python-sdk.md
    - MCP Server: api/mcp-server.md
  - Examples:
    - Example PRDs: examples/prd-examples.md
    - Generated Templates: examples/generated-templates.md
  - Developer Guide:
    - Contributing: developer-guide/contributing.md
    - Testing: developer-guide/testing.md
    - Architecture Decisions: developer-guide/architecture-decisions.md

# Extra configuration
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moinsen-dev/marvin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/marvin_tool
  analytics:
    provider: google
    property: G-XXXXXXXXXX

# CSS overrides
extra_css:
  - stylesheets/extra.css

# JavaScript overrides
extra_javascript:
  - javascripts/extra.js